# Generated by Django 5.1.4 on 2024-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
