# Generated by Django 5.1.4 on 2024-12-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_sale_product_salepoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
