# Generated by Django 5.1.4 on 2024-12-13 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 13, 16, 16, 9, 511000, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
