# Generated by Django 5.1.4 on 2024-12-13 16:23

from django.db import migrations

# from website.models import Product # NOOOO


def forwards(apps, schema_editor):
    Product = apps.get_model("website", "Product")
    if not Product.objects.filter(title="Demo product").exists():
        Product.objects.create(title="Demo product", price=1)


def backwards(apps, schema_editor):
    Product = apps.get_model("website", "Product")
    Product.objects.filter(title="Demo product").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_product_created_datetime"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
